#
# Reduce the size of the `vendor` directory excluding unused packages, tests and
# other files that aren't needed.
#
[prune]
  go-tests = true
  non-go = true
  unused-packages = true

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "1.0.1"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.2"

[[constraint]]
  name = "github.com/antlr/antlr4"
  version = "4.7.1"

# This is needed to avoid a crash in `dep ensure`, see here for more details:
# https://github.com/golang/dep/issues/1799
[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "gopkg.in/fsnotify/fsnotify.v1"
